# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /opt/Server/gb_proto_parse/gb_nbe_proto

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /opt/Server/gb_proto_parse/gb_nbe_proto

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/Server/gb_proto_parse/gb_nbe_proto/CMakeFiles /opt/Server/gb_proto_parse/gb_nbe_proto/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/Server/gb_proto_parse/gb_nbe_proto/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gb_gmm_sm_test

# Build rule for target.
gb_gmm_sm_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gb_gmm_sm_test
.PHONY : gb_gmm_sm_test

# fast build rule for target.
gb_gmm_sm_test/fast:
	$(MAKE) -f CMakeFiles/gb_gmm_sm_test.dir/build.make CMakeFiles/gb_gmm_sm_test.dir/build
.PHONY : gb_gmm_sm_test/fast

#=============================================================================
# Target rules for targets named gb_l2_test

# Build rule for target.
gb_l2_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gb_l2_test
.PHONY : gb_l2_test

# fast build rule for target.
gb_l2_test/fast:
	$(MAKE) -f CMakeFiles/gb_l2_test.dir/build.make CMakeFiles/gb_l2_test.dir/build
.PHONY : gb_l2_test/fast

#=============================================================================
# Target rules for targets named gb_protocol_test

# Build rule for target.
gb_protocol_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gb_protocol_test
.PHONY : gb_protocol_test

# fast build rule for target.
gb_protocol_test/fast:
	$(MAKE) -f CMakeFiles/gb_protocol_test.dir/build.make CMakeFiles/gb_protocol_test.dir/build
.PHONY : gb_protocol_test/fast

#=============================================================================
# Target rules for targets named gb_proto

# Build rule for target.
gb_proto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gb_proto
.PHONY : gb_proto

# fast build rule for target.
gb_proto/fast:
	$(MAKE) -f gen/CMakeFiles/gb_proto.dir/build.make gen/CMakeFiles/gb_proto.dir/build
.PHONY : gb_proto/fast

gb_gmm_sm_test.o: gb_gmm_sm_test.c.o
.PHONY : gb_gmm_sm_test.o

# target to build an object file
gb_gmm_sm_test.c.o:
	$(MAKE) -f CMakeFiles/gb_gmm_sm_test.dir/build.make CMakeFiles/gb_gmm_sm_test.dir/gb_gmm_sm_test.c.o
.PHONY : gb_gmm_sm_test.c.o

gb_gmm_sm_test.i: gb_gmm_sm_test.c.i
.PHONY : gb_gmm_sm_test.i

# target to preprocess a source file
gb_gmm_sm_test.c.i:
	$(MAKE) -f CMakeFiles/gb_gmm_sm_test.dir/build.make CMakeFiles/gb_gmm_sm_test.dir/gb_gmm_sm_test.c.i
.PHONY : gb_gmm_sm_test.c.i

gb_gmm_sm_test.s: gb_gmm_sm_test.c.s
.PHONY : gb_gmm_sm_test.s

# target to generate assembly for a file
gb_gmm_sm_test.c.s:
	$(MAKE) -f CMakeFiles/gb_gmm_sm_test.dir/build.make CMakeFiles/gb_gmm_sm_test.dir/gb_gmm_sm_test.c.s
.PHONY : gb_gmm_sm_test.c.s

gb_l2_test.o: gb_l2_test.c.o
.PHONY : gb_l2_test.o

# target to build an object file
gb_l2_test.c.o:
	$(MAKE) -f CMakeFiles/gb_l2_test.dir/build.make CMakeFiles/gb_l2_test.dir/gb_l2_test.c.o
.PHONY : gb_l2_test.c.o

gb_l2_test.i: gb_l2_test.c.i
.PHONY : gb_l2_test.i

# target to preprocess a source file
gb_l2_test.c.i:
	$(MAKE) -f CMakeFiles/gb_l2_test.dir/build.make CMakeFiles/gb_l2_test.dir/gb_l2_test.c.i
.PHONY : gb_l2_test.c.i

gb_l2_test.s: gb_l2_test.c.s
.PHONY : gb_l2_test.s

# target to generate assembly for a file
gb_l2_test.c.s:
	$(MAKE) -f CMakeFiles/gb_l2_test.dir/build.make CMakeFiles/gb_l2_test.dir/gb_l2_test.c.s
.PHONY : gb_l2_test.c.s

gb_protocol_test.o: gb_protocol_test.c.o
.PHONY : gb_protocol_test.o

# target to build an object file
gb_protocol_test.c.o:
	$(MAKE) -f CMakeFiles/gb_protocol_test.dir/build.make CMakeFiles/gb_protocol_test.dir/gb_protocol_test.c.o
.PHONY : gb_protocol_test.c.o

gb_protocol_test.i: gb_protocol_test.c.i
.PHONY : gb_protocol_test.i

# target to preprocess a source file
gb_protocol_test.c.i:
	$(MAKE) -f CMakeFiles/gb_protocol_test.dir/build.make CMakeFiles/gb_protocol_test.dir/gb_protocol_test.c.i
.PHONY : gb_protocol_test.c.i

gb_protocol_test.s: gb_protocol_test.c.s
.PHONY : gb_protocol_test.s

# target to generate assembly for a file
gb_protocol_test.c.s:
	$(MAKE) -f CMakeFiles/gb_protocol_test.dir/build.make CMakeFiles/gb_protocol_test.dir/gb_protocol_test.c.s
.PHONY : gb_protocol_test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... gb_gmm_sm_test"
	@echo "... gb_l2_test"
	@echo "... gb_protocol_test"
	@echo "... rebuild_cache"
	@echo "... gb_proto"
	@echo "... gb_gmm_sm_test.o"
	@echo "... gb_gmm_sm_test.i"
	@echo "... gb_gmm_sm_test.s"
	@echo "... gb_l2_test.o"
	@echo "... gb_l2_test.i"
	@echo "... gb_l2_test.s"
	@echo "... gb_protocol_test.o"
	@echo "... gb_protocol_test.i"
	@echo "... gb_protocol_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

